### PR TITLE
[feature] Added general setting to disable all notifications #148

### LINKED ISSUE #148: [feature] Allow to disable notifications for all organizations or keep everything disabled except notifications for specific organizations
Current buggy situation:

- superadmin A decides to receive no email notifications or no notifications at all, to do so, they must explicitly disable all notifications (which is time consuming)
- a new organization called Snakeoil is created in the system
- superadmin A gets the notification settings records created for Snakeoil, defaulting to enabled notifications
- superadmin A starts receiving notifications for Snakeoil even though they decided to turn notifications off 

**Possible solution:**

Introduce a general setting, which allows to turn off web and/or email notifications for all organizations (eg: a record like `NotificationSettings(organization=None, type=None, user=user, email=False, web=True)` could indicate that email notifications are disabled but web notifications are enabled for a specific user, regardless of the organization).

When all notifications are turned off using this method, the system must flag all notification settings relating to the different orgs as disabled.
Vice versa, if all notifications are turned on, the system must flag all notification settings relating to the different orgs as enabled.

When a user disables all notifications for all orgs, it must be possible for the user to enable notifications for a particular organization they're interested in, so that all notifications are disabled except for specific notifications for a specific organization.
This would allow a user to have notifications enabled only for a particular organization while maintaining notifications disabled for all other organizations, even for organizations that would be created in the future.

This feature must be available through the REST API, that is, it shall be possible to enable/disable all notifications for all orgs  via the REST API with one HTTP request.

### PR DESCRIPTION
**Pull request by niteshsinha17**
Created a new model named `General Setting` through which we can disable email OR/AND web notifications for all the organization whether it is created after or before disabling.

Also, I have written tests for it. 
I think we may need to write code for API too and also need to mention this feature in the documentation. 
Before doing this it will be great if you give consent to this solution.   

closes #148

### CODE REVIEW

**Comment by pandafy** [comment]
@niteshsinha17 the changes that you have made in this PR were not expected. 

Read this discussion to get a better idea of what is expected from the issue: https://github.com/openwisp/openwisp-notifications/pull/69#pullrequestreview-471188099

**Comment by niteshsinha17** [comment]
> @niteshsinha17 the changes that you have made in this PR were not expected.
> 
> Read this discussion to get a better idea of what is expected from the issue: [#69 (review)](https://github.com/openwisp/openwisp-notifications/pull/69#pullrequestreview-471188099)

Okay, I will check and will make changes according to it.

**Comment by niteshsinha17** [comment]
@pandafy from this https://github.com/openwisp/openwisp-notifications/pull/69#pullrequestreview-471188099 I have concluded a few things that I wanted to share with you.

-  I need to create that `All` setting which was removed in this PR but this time the need is to disable all notifications?
- If yes then we will again come into the confusing situation which was mentioned in the above PR.
>  if notifications are enabled in ALL but not enabled in the org, which setting overrides which?

If the above points are true then I think this could be a solution.
- That 'All' setting should not generate automatically. It will be created by the user by creating a new notification setting to disable all notifications.
- If a user disables notifications for all organizations for a particular type then we can check the record before setting the notification.
- If he enables notifications both web and email for all organizations then we will delete that setting.

What do you think about it?

**Comment by pandafy** [comment]
@nemesisdesign will be the right person to answer this query.

**Comment by nemesifier** [comment]
Closing as we're working on this in GSoC24. Thanks Nitesh!

**Pull request closed without merging**
