### PR TITLE
[ux] Improvements to notification widget

### PR DESCRIPTION
**Pull request by nemesisdesign**
- improved readability of notification date and time
- fixed JS issue when clicking on unread items
- changed colors to be more neutral

### CODE REVIEW

**Comment by nemesisdesign** [comment]
Below a few screenshots to show how the changes look.

### Notification widget

Screenshot from 2020-08-05 13-34-27

Hovering on an element makes it brighter (white background and black font).
This works well also when using different colors (customized themes).

notifications

### Notification toasts

Screenshot from 2020-08-05 19-40-47
Screenshot from 2020-08-05 19-42-05
Screenshot from 2020-08-05 19-42-40

**Comment by nemesisdesign** [comment]
Merging to speed things up, feel free to introduce improvements if you think it's needed.

**Comment by pandafy** [comment]
@nemesisdesign color choice looks awesome. I used a little too bright colors before. :laughing: 

I have one question.  Was success type got left out or is it deliberate?
Screenshot from 2020-08-06 17-19-01

**Comment by nemesisdesign** [comment]
> @nemesisdesign color choice looks awesome. I used a little too bright colors before. 
> 
> I have one question. Was success type got left out or is it deliberate?
> Screenshot from 2020-08-06 17-19-01

I forgot about it, I think we can make it like the error one but with a green background.

**Pull request merged**
