### PR TITLE
[change:ux] Restyled notification email template #187

### LINKED ISSUE #187: [change:ux] Restyle notification email template according to new theme
Let's restyle the notification email template so it's consistent with the new light theme.
Nothing complicated, light background, standard logo (not inverted), we should add a call to action button.

### PR DESCRIPTION
**Pull request by codesankalp**
Made email template similar to openwisp new theme.
Added call to action button.

Closes #187

### CODE REVIEW

**Comment by codesankalp** [comment]
# Mobile
mobile

# Desktop

image

**Comment by codesankalp** [comment]
The table is set to width:100% which may make the table wide enough on a big screen. Should I fix the width?

**Comment by codesankalp** [comment]
**Desktop**:
image

**Mobile**:

img

**Review by nemesisdesign — COMMENTED** [review]
I improved it a bit:

Screenshot from 2021-09-18 15-03-01

Please double check and let me know.

I'm testing it through a static HTML file:

```html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <style type="text/css">
    body {
      min-width: 250px;
      background: #ffe5e5;
      margin: 0;
      padding: 0;
    }

    .container{
      background: #ffe5e5;
      height: 100%;
      min-height: 400px;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .box{
      width: auto;
      padding: 60px 40px;
      background-color: #fcfcfc;
      box-sizing: border-box;
      box-shadow: 0 15px 25px rgba(256,256, 256,.5);
      border-radius: 10px;
      margin: auto;
    }

    .logo-container{
      text-align: center;
      margin-bottom: 25px;
    }

    .logo {
      max-width: 230px;
    }

    .call-to-action{
      text-align: center;
      margin-top: 30px;
    }

    .subject{
      font-size: medium;
      font-weight: 700;
      margin: 20px 0;
    }

    .msg{
      color: #1b1818;
      margin: 20px 0;
    }

    .btn{
      appearance: button;
      text-decoration: none;
      color: #fff!important;
      background: #333;
      border-radius: 4px;
      border: 0;
      padding: 10px 15px;
      font-weight: 500;
      font-size: 14px;
      text-transform: uppercase;
    }

    .btn:hover, .btn:focus {
      background: #000;
      outline: 0 none;
      background: rgba(51, 51, 51, 0.7);
    }

    a:link:hover {
      text-decoration: none;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="box">
      <div class="logo-container">
        <img src="https://github.com/openwisp/openwisp-notifications/blob/4afa770670e4c31736236ac4ee2cf3d1ae55fed6/openwisp_notifications/static/openwisp-notifications/images/openwisp-logo.png?raw=true" alt="Logo" id="logo" class="logo">
      </div>
      <div class="subject">
        [OpenWISP] RECOVERY: ap-b536-comu-02 CPU usage has returned to normal levels
      </div>
      <div class="msg">
        The device <a href="#">ap-b536-comu-02</a> CPU usage has returned to normal levels.
      </div>
      <div class="call-to-action">
        <a href="#" class="btn">Find out more</a>
      </div>
    </div>
  </div>
</body>
</html>
```

We will have to upadte this image:



But I would do as we've been doing recently in other repos: remove the file from master and upload it in a branch dedicated for storing docs images.

**Comment by codesankalp** [comment]
> Please double check and let me know.

The box is not showing in the center vertically when I send a mail using the updated template.

**Comment by codesankalp** [comment]
Updated README: https://github.com/openwisp/openwisp-notifications/tree/docs
Should I delete all the images in this PR or create a new PR for this?

**Review by nemesisdesign — COMMENTED** [review]
> Updated README: https://github.com/openwisp/openwisp-notifications/tree/docs
> Should I delete all the images in this PR or create a new PR for this?

A new PR please (except this new image that is related to this PR, you can change that one in this PR since it's related and it's good to keep related changes together).

**Review by nemesisdesign — COMMENTED** [review]
I am testing this, I am waiting to receive a real notification, will update this soon.

**Review by nemesisdesign — APPROVED** [review]
Thanks!

**Pull request merged**
