### PR TITLE
[docs] Updated README to use images on docs branch

### PR DESCRIPTION
**Pull request by codesankalp**

### CODE REVIEW

**Review by pandafy — CHANGES_REQUESTED** [review]
Let's the keep the changes atomic and remove email-template.png from this PR.

**Review by pandafy — CHANGES_REQUESTED** [review]
Delete these images from the master branch as well.

**Comment by codesankalp** [comment]
> Let's the keep the changes atomic and remove email-template.png from this PR.
> Delete these images from the master branch as well.

The branch is in the upstream, If I will remove those images from the docs branch then it will be gone from the docs branch.
And we need all the images in the docs branch to display in the master branch?

**Comment by pandafy** [comment]
> The branch is in the upstream, If I will remove those images from the docs branch then it will be gone from the docs branch.
> And we need all the images in the docs branch to display in the master branch?

I didn't notice that you have opened this PR from docs branch. Can you please open another PR from a different branch (not docs)? That way we will be able to keep all of the work atomic.

**Comment by codesankalp** [comment]
Created https://github.com/openwisp/openwisp-notifications/pull/197

**Pull request closed without merging**
